export const userTypes = {
  GET_USERS: "GET_USERS",
  CHANGE_FOLLOW_STATUS: "CHANGE_FOLLOW_STATUS",
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
  IS_FETCHING: "IS_FETCHING",
  SET_SEARCHING_NAME: "SET_SEARCHING_NAME",
  CLEANING_STATE: "CLEANING_STATE",
};

export const profileTypes = {
  GET_PROFILE: "GET_PROFILE",
  IS_FETCHING: "IS_FETCHING",
  SET_USERID: "SET_USERID",
  SET_STATUS: "SET_STATUS",
  GET_FOLLOW: "GET_FOLLOW",
  SET_PHOTO: "SET_PHOTO",
  SET_CONTACTS: "SET_CONTACTS",
};

export const friendsTypes = {
  GET_FRIENDS: "GET_FRIENDS",
  IS_FETCHING: "IS_FETCHING",
  UN_FOLLOW: "UN_FOLLOW",
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
  SET_SEARCHING_NAME: "SET_SEARCHING_NAME",
  CLEANING_STATE: "CLEANING_STATE",
};

export const authTypes = {
  SET_USER_DATA: "SET_USER_DATA",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  IS_AUTH: "IS_AUTH",
};
